In [4]:
import pandas as pd
import warnings

In [9]:
pd.set_option('display.max_columns', None)

In [5]:
warnings.filterwarnings(action='ignore')

In [7]:
df=pd.read_csv('soccerDB4.csv')

In [15]:
temp=df[1139:]

In [18]:
temp=temp.drop(columns='Unnamed: 0')

In [20]:
temp=temp.reset_index()

In [21]:
temp=temp.drop(columns='index')

In [53]:
#for n in games:
    ['round'][contador]
        if ['round'][contador] > contador_rodada:
            
            
for n in range():
    temp['round'][contador] 
    temp['ht_previuos_classification']=['ht_current_classification'] in ['round'][contador-1]
    
    temp[(temp['ht_current_classification'][contador] in temp['round'] > temp['ht_current_classification'][contador] in temp[temp['round']-1])]
    
    
    if temp['ht_current_classification'['round']]['contador'] > temp[['ht_current_classification',['round'][-1]]]   
    
    temp['ht_current_classification']['contador'] 
    
    temp['round'][contador]
    temp['home_team'][contador]

    temp['away_team']

IndentationError: unexpected indent (<ipython-input-53-9cf5b6a1302d>, line 2)

In [77]:
temp.groupby(['round','home_team','ht_current_classification']).count()

                                               a_Ataques  a_Ataques perigosos  \
round home_team     ht_current_classification
1     América MG    18                                 1                    1
                    20                                 1                    1
      Atlético MG   4                                  1                    1
                    5                                  1                    1
      Atlético PR   7                                  1                    1
                    8                                  1                    1
                    10                                 1                    1
      Avaí          17                                 1                    1
                    18                                 1                    1
      Bahia         12                                 1                    1
                    18                                 1                    1
      Botafogo      5                                  1                    1
                    9                                  1                    1
      Chapecoense   14                                 1                    1
                    15                                 1                    1
      Corinthians   1                                  1                    1
                    7                                  1                    1
                    10                                 1                    1
                    13                                 1                    1
      Coritiba      11                                 1                    1
                    15                                 1                    1
                    17                                 1                    1
      Criciúma      14                                 1                    1
                    20                                 1                    1
      Cruzeiro      1                                  1                    1
                    5                                  1                    1
                    8                                  2                    2
      Figueirense   18                                 1                    1
      Flamengo      3                                  1                    1
                    6                                  1                    1
...                                                  ...                  ...
38    Fluminense    12                                 1                    1
                    14                                 1                    1
      Goiás         4                                  1                    1
                    13                                 1                    1
                    19                                 1                    1
      Grêmio        4                                  1                    1
                    7                                  1                    1
                    8                                  1                    1
      Internacional 5                                  1                    1
                    14                                 1                    1
      Joinville     20                                 1                    1
      Náutico       20                                 1                    1
      Palmeiras     1                                  1                    1
                    16                                 1                    1
      Paraná        20                                 1                    1
      Ponte Preta   10                                 2                    2
      Portuguesa    13                                 1                    1
      Santos        3                                  1                    1
                    4                                  1                    1
                    7                                  1                    1
      Sport         11                                 1                    1
                    16                                 1                    1
                    17                                 1                    1
                    18                                 1                    1
      São Paulo     9                                  1                    1
                    11                                 1                    1
                    12                                 1                    1
      Vasco         7                                  1                    1
      Vitória       15                                 2                    2
                    17                                 1                    1

                                               a_Cartões amarelos  \
round home_team     ht_current_classification
1     América MG    18                                          1
                    20                                          0
      Atlético MG   4                                           1
                    5                                           0
      Atlético PR   7                                           1
                    8                                           1
                    10                                          1
      Avaí          17                                          1
                    18                                          1
      Bahia         12                                          1
                    18                                          1
      Botafogo      5                                           1
                    9                                           1
      Chapecoense   14                                          1
                    15                                          1
      Corinthians   1                                           1
                    7                                           1
                    10                                          1
                    13                                          0
      Coritiba      11                                          1
                    15                                          1
                    17                                          1
      Criciúma      14                                          1
                    20                                          1
      Cruzeiro      1                                           1
                    5                                           1
                    8                                           2
      Figueirense   18                                          1
      Flamengo      3                                           1
                    6                                           1
...                                                           ...
38    Fluminense    12                                          1
                    14                                          1
      Goiás         4                                           1
                    13                                          1
                    19                                          1
      Grêmio        4                                           1
                    7                                           1
                    8                                           1
      Internacional 5                                           1
                    14                                          1
      Joinville     20                                          1
      Náutico       20                                          1
      Palmeiras     1                                           1
                    16                                          1
      Paraná        20                                          1
      Ponte Preta   10                                          2
      Portuguesa    13                                          1
      Santos        3                                           1
                    4                                           1
                    7                                           1
      Sport         11                                          1
                    16                                          1
                    17                                          1
                    18                                          1
      São Paulo     9                                           1
                    11                                          1
                    12                                          1
      Vasco         7                                           1
      Vitória       15                                          2
                    17                                          1

                                               a_Cartões vermelhos  \
round home_team     ht_current_classification
1     América MG    18                                           0
                    20                                           0
      Atlético MG   4                                            0
                    5                                            0
      Atlético PR   7                                            0
                    8                                            0
                    10                                           0
      Avaí          17                                           0
                    18                                           0
      Bahia         12                                           0
                    18                                           0
      Botafogo      5                                            0
                    9                                            0
      Chapecoense   14                                           0
                    15                                           0
      Corinthians   1                                            0
                    7                                            0
                    10                                           0
                    13                                           0
      Coritiba      11                                           0
                    15                                           1
                    17                                           0
      Criciúma      14                                           0
                    20                                           0
      Cruzeiro      1                                            0
                    5                                            0
                    8                                            1
      Figueirense   18                                           0
      Flamengo      3                                            1
                    6                                            0
...                                                            ...
38    Fluminense    12                                           0
                    14                                           0
      Goiás         4                                            1
                    13                                           0
                    19                                           0
      Grêmio        4                                            0
                    7                                            1
                    8                                            0
      Internacional 5                                            0
                    14                                           0
      Joinville     20                                           0
      Náutico       20                                           0
      Palmeiras     1                                            0
                    16                                           0
      Paraná        20                                           1
      Ponte Preta   10                                           0
      Portuguesa    13                                           0
      Santos        3                                            0
                    4                                            0
                    7                                            0
      Sport         11                                           0
                    16                                           0
                    17                                           0
                    18                                           0
      São Paulo     9                                            0
                    11                                           0
                    12                                           0
      Vasco         7                                            0
      Vitória       15                                           0
                    17                                           0

                                               a_Chutes a gol  \
round home_team     ht_current_classification
1     América MG    18                                      1
                    20                                      1
      Atlético MG   4                                       1
                    5                                       1
      Atlético PR   7                                       1
                    8                                       1
                    10                                      1
      Avaí          17                                      1
                    18                                      1
      Bahia         12                                      1
                    18                                      1
      Botafogo      5                                       1
                    9                                       1
      Chapecoense   14                                      1
                    15                                      1
      Corinthians   1                                       0
                    7                                       1
                    10                                      1
                    13                                      1
      Coritiba      11                                      1
                    15                                      1
                    17                                      1
      Criciúma      14                                      1
                    20                                      1
      Cruzeiro      1                                       1
                    5                                       1
                    8                                       2
      Figueirense   18                                      1
      Flamengo      3                                       1
                    6                                       1
...                                                       ...
38    Fluminense    12                                      1
                    14                                      1
      Goiás         4                                       1
                    13                                      1
                    19                                      1
      Grêmio        4                                       1
                    7                                       1
                    8                                       1
      Internacional 5                                       1
                    14                                      1
      Joinville     20                                      1
      Náutico       20                                      1
      Palmeiras     1                                       1
                    16                                      1
      Paraná        20                                      1
      Ponte Preta   10                                      2
      Portuguesa    13                                      1
      Santos        3                                       1
                    4                                       1
                    7                                       1
      Sport         11                                      1
                    16                                      1
                    17                                      1
                    18                                      1
      São Paulo     9                                       1
                    11                                      1
                    12                                      1
      Vasco         7                                       1
      Vitória       15                                      2
                    17                                      1

                                               a_Chutes ao ferro  \
round home_team     ht_current_classification
1     América MG    18                                         0
                    20                                         0
      Atlético MG   4                                          0
                    5                                          0
      Atlético PR   7                                          0
                    8                                          0
                    10                                         1
      Avaí          17                                         1
                    18                                         1
      Bahia         12                                         0
                    18                                         1
      Botafogo      5                                          0
                    9                                          0
      Chapecoense   14                                         1
                    15                                         0
      Corinthians   1                                          1
                    7                                          0
                    10                                         0
                    13                                         0
      Coritiba      11                                         0
                    15                                         0
                    17                                         1
      Criciúma      14                                         1
                    20                                         0
      Cruzeiro      1                                          0
                    5                                          0
                    8                                          0
      Figueirense   18                                         1
      Flamengo      3                                          0
                    6                                          0
...                                                          ...
38    Fluminense    12                                         1
                    14                                         1
      Goiás         4                                          1
                    13                                         0
                    19                                         0
      Grêmio        4                                          0
                    7                                          1
                    8                                          1
      Internacional 5                                          0
                    14                                         1
      Joinville     20                                         1

In [68]:
times2=times.drop(columns=times[0:])#times=

In [78]:
times2=times2.reset_index()

In [79]:
for times2

      round  ht_current_classification      home_team
0         1                          1    Corinthians
1         1                          1       Cruzeiro
2         1                          1      Palmeiras
3         1                          2         Grêmio
4         1                          2      Palmeiras
5         1                          2      São Paulo
6         1                          3       Flamengo
7         1                          3         Grêmio
8         1                          3  Internacional
9         1                          4    Atlético MG
10        1                          4         Grêmio
11        1                          4      São Paulo
12        1                          5    Atlético MG
13        1                          5       Botafogo
14        1                          5       Cruzeiro
15        1                          5      São Paulo
16        1                          5        Vitória
17        1                          6       Flamengo
18        1                          6     Fluminense
19        1                          6          Sport
20        1                          7    Atlético PR
21        1                          7    Corinthians
22        1                          7         Santos
23        1                          8    Atlético PR
24        1                          8       Cruzeiro
25        1                          9       Botafogo
26        1                          9      Palmeiras
27        1                          9         Santos
28        1                         10    Atlético PR
29        1                         10    Corinthians
...     ...                        ...            ...
2112     38                         11          Sport
2113     38                         11      São Paulo
2114     38                         12          Bahia
2115     38                         12    Figueirense
2116     38                         12       Flamengo
2117     38                         12     Fluminense
2118     38                         12      São Paulo
2119     38                         13    Atlético PR
2120     38                         13          Ceará
2121     38                         13       Cruzeiro
2122     38                         13          Goiás
2123     38                         13     Portuguesa
2124     38                         14       Coritiba
2125     38                         14     Fluminense
2126     38                         14  Internacional
2127     38                         15       Coritiba
2128     38                         15        Vitória
2129     38                         16    Chapecoense
2130     38                         16      Palmeiras
2131     38                         16          Sport
2132     38                         17    Figueirense
2133     38                         17          Sport
2134     38                         17        Vitória
2135     38                         18          Sport
2136     38                         19       Botafogo
2137     38                         19          Goiás
2138     38                         20    Atlético GO
2139     38                         20      Joinville
2140     38                         20        Náutico
2141     38                         20         Paraná

[2142 rows x 3 columns]