In [1]:
import pandas as pd
import warnings

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
warnings.filterwarnings(action='ignore')

In [59]:
df=pd.read_csv('soccerDB4.csv')

In [60]:
df=df.drop('Unnamed: 0',axis=1)

In [62]:
df['datetime']=pd.to_datetime(df['datetime'],format='%Y%m%d')

In [7]:
df_2013=df[(df.datetime.dt.year > 2012) & (df.datetime.dt.year < 2014)]

In [17]:
df_2014=df[(df.datetime.dt.year > 2013) & (df.datetime.dt.year < 2015)]

In [27]:
df_2015=df[(df.datetime.dt.year > 2014) & (df.datetime.dt.year < 2016)]

In [28]:
df_2016=df[(df.datetime.dt.year > 2015) & (df.datetime.dt.year < 2017)]

In [65]:
df_2017=df[(df.datetime.dt.year > 2016) & (df.datetime.dt.year < 2018)]

In [76]:
df_2018=df[(df.datetime.dt.year > 2017) & (df.datetime.dt.year < 2019)]

In [77]:
df_2018=df_2018.reset_index()

In [78]:
df_2018=df_2018.drop(columns='index',axis=0)

In [79]:
df_2018=df_2018.rename(columns={'h_Chutes a gol':'h_chutes_a_gol','a_Chutes a gol':'a_chutes_a_gol'})

In [80]:
df_2018['ht_eff_of']=1
df_2018['ht_eff_of']=df_2017['ht_eff_of'].astype(float)

In [81]:
df_2018['at_eff_of']=1
df_2018['at_eff_of']=df_2017['at_eff_of'].astype(float)

In [82]:
contador=0
for n in range(380):
    time=df_2018['home_team'][contador]
    grupo=df_2018.groupby(df_2018['home_team']==time).sum()
    conta=grupo.home_team_score[True] /grupo.h_chutes_a_gol[True]
    df_2018['ht_eff_of'][contador]=conta
    contador+=1

In [83]:
contador=0
for n in range(371):
    time=df_2018['away_team'][contador]
    grupo=df_2018.groupby(df_2018['away_team']==time).sum()
    conta=grupo.away_team_score[True] /grupo.a_chutes_a_gol[True]
    df_2018['at_eff_of'][contador]=conta
    contador+=1

In [84]:
df_2018

,a_Ataques,a_Ataques perigosos,a_Cartões amarelos,a_Cartões vermelhos,a_chutes_a_gol,a_Chutes ao ferro,a_Chutes bloqueados,a_Chutes fora,a_Escanteios,a_Faltas,a_Gols,a_Impedimentos,a_Laterais,a_Pênaltis,a_Segundo cartão amarelo,a_Substituições,a_Tiros de meta,a_Tiros-livres,at_current_classification,at_current_draws_away,at_current_draws_global,at_current_draws_home,at_current_loss_away,at_current_loss_global,at_current_loss_home,at_current_wins_away,at_current_wins_global,at_current_wins_home,at_games_without_draw_away,at_games_without_draw_global,at_games_without_draw_home,at_games_without_lose_away,at_games_without_lose_global,at_games_without_lose_home,at_games_without_win_away,at_games_without_win_global,at_games_without_win_home,away_team,away_team_score,city,datetime,h_Ataques,h_Ataques perigosos,h_Cartões amarelos,h_Cartões vermelhos,h_chutes_a_gol,h_Chutes ao ferro,h_Chutes bloqueados,h_Chutes fora,h_Escanteios,h_Faltas,h_Gols,h_Impedimentos,h_Laterais,possession,h_Pênaltis,h_Segundo cartão amarelo,h_Substituições,h_Tiros de meta,h_Tiros-livres,home_team,home_team_score,ht_current_classification,ht_current_draws_away,ht_current_draws_global,ht_current_draws_home,ht_current_loss_away,ht_current_loss_global,ht_current_loss_home,ht_current_wins_away,ht_current_wins_global,ht_current_wins_home,ht_games_without_draw_away,ht_games_without_draw_global,ht_games_without_draw_home,ht_games_without_lose_away,ht_games_without_lose_global,ht_games_without_lose_home,ht_games_without_win_away,ht_games_without_win_global,ht_games_without_win_home,referee,round,stadium,home_player_1,home_player_2,home_player_3,home_player_4,home_player_5,home_player_6,home_player_7,home_player_8,home_player_9,home_player_10,home_player_11,away_player_1,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11,sub_home_player_1,sub_home_player_2,sub_home_player_3,sub_home_player_4,sub_home_player_5,sub_home_player_6,sub_home_player_7,sub_home_player_8,sub_home_player_9,sub_home_player_10,sub_home_player_11,sub_home_player_12,sub_away_player_1,sub_away_player_2,sub_away_player_3,sub_away_player_4,sub_away_player_5,sub_away_player_6,sub_away_player_7,sub_away_player_8,sub_away_player_9,sub_away_player_10,sub_away_player_11,sub_away_player_12,result,int_date,ht_eff_of,at_eff_of
0,57.0,30.0,1.0,1.0,3.0,NaN,0.0,2.0,4.0,15.0,1.0,2.0,12.0,NaN,NaN,3.0,5.0,20.0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Grêmio,1,"Belo Horizonte, Minas Gerais",2018-04-14,54.0,44.0,3.0,0.0,8.0,NaN,1.0,5.0,7.0,20.0,0.0,0.0,13.0,42.0,NaN,NaN,3.0,3.0,17.0,Cruzeiro,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Rodolpho Toski Marques,1,Estádio Governador Magalhães Pinto,"('person-8961', 'Fábio')","('person-64406', 'Léo')","('person-71117', 'Edílson')","('person-71699', 'Dedé')","('person-9319', 'Egídio')","('person-48535', 'Thiago Neves')","('person-65376', 'Robinho')","('person-247639', 'G. De Arrascaeta')","('person-14311', 'A. Cabral')","('person-9112', 'Henrique')","('person-3596', 'Rafael Sóbis')","('person-9187', 'Marcelo Grohe')","('person-65193', 'Paulo Miranda')","('person-9064', 'Léo Moura')","('person-122865', 'W. Kannemann')","('person-172590', 'Bruno Cortez')","('person-9138', 'Cícero')","('person-174110', 'Ramiro')","('person-288085', 'Arthur')","('person-16465', 'Maicon')","('person-75403', 'André')","('person-327852', 'Everton')","('person-97650', 'Rafael')","('person-431776', 'Lucas França')","('person-80390', 'Manoel')","('person-282477', 'Marcelo Hermes')","('person-526594', 'Vitinho')","('person-65012', 'Digão')","('person-69072', 'F. Mancuello')","('person-94923', 'Bruno Silva')","('person-233956', 'Lucas Silva')","('person-232741', 'Sassá')","('person-4987', 'Rafael Marques')",None,"('person-64355', 'Paulo Victor')","('person-115239', 'Bressan')","('person-173980', 'Mádson')","('person-10265', 'Marcelo Oliveira')","('person-170956', 'Michel')","('person-532391', 'Thonny Anderson')","('person-8978', 'Maicosuel')","('person-415615', 'Lima')","('person-400791', 'Jaílson')","('person-276507', 'Alisson')","('person-33287', 'Jael')",None,lose,0,0.304878,0.176471
1,38.0,30.0,2.0,1.0,4.0,NaN,0.0,3.0,5.0,9.0,2.0,2.0,19.0,0.0,NaN,3.0,11.0,25.0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Flamengo,2,"Salvador, Bahia",2018-04-14,48.0,41.0,3.0,0.0,3.0,NaN,2.0,9.0,4.0,23.0,2.0,2.0,18.0,63.0,1.0,NaN,3.0,4.0,11.0,Vitória,2,19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Wagner Reway,1,Estádio Manoel Barradas,"('person-410989', 'Caíque')","('person-73209', 'Kanu')","('person-284092', 'Ramon')","('person-9116', 'Pedro Botelho')","('person-330875', 'Rodrigo Andrade')","('person-1987', 'A. Baumjohann')","('person-333198', 'Yago')","('person-171307', 'Uillian Correia')","('person-32925', 'Willian Farias')","('person-297878', 'Denílson')","('person-67280', 'Rhayner')","('person-8905', 'Diego Alves')","('person-33271', 'Réver')","('person-192705', 'Rodinei')","('person-132', 'Juan')","('person-225802', 'Renê')","('person-9040', 'Everton Ribeiro')","('person-2027', 'Diego')","('person-84154', 'G. Cuéllar')","('person-438313', 'Lucas Paquetá')","('person-112183', 'Henrique Dourado')","('person-474972', 'Vinícius Júnior')","('person-396908', 'Ronaldo')","('person-71994', 'Fernando Miguel')","('person-288072', 'Jeferson')","('person-399761', 'Bruno')","('person-192640', 'Walisson')","('person-9106', 'Lucas')","('person-79754', 'Juninho')","('person-328123', 'José Welison')","('person-405660', 'Lucas Marques')","('person-388491', 'Nickson')","('person-180826', 'Guilherme Costa')","('person-171484', 'Jonatas Belusso')","('person-197635', 'César')","('person-287910', 'Thiago')","('person-503140', 'Thuler')","('person-32800', 'Pará')","('person-436474', 'Léo Duarte')","('person-176390', 'M. Trauco')","('person-230411', 'Willian Arão')","('person-474926', 'Jean Lucas')","('person-233411', 'Jonas')","('person-191206', 'Geuvânio')","('person-290500', 'M. Moreno')","('person-474973', 'Lincoln')",draw,0,0.323529,0.341176
2,53.0,36.0,1.0,NaN,2.0,NaN,4.0,4.0,2.0,5.0,0.0,0.0,21.0,NaN,NaN,3.0,16.0,9.0,15,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Ceará,0,"São Paulo, São Paulo",2018-04-14,69.0,53.0,0.0,NaN,1.0,NaN,5.0,13.0,4.0,8.0,2.0,1.0,21.0,52.0,NaN,NaN,3.0,7.0,5.0,Santos,2,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Rodrigo D'Alonso Ferreira,1,Estádio Municipal Paulo Machado de Carvalho,"('person-32900', 'Vanderlei')","('person-335724', 'Daniel Guedes')","('person-430035', 'Lucas Verissimo')","('person-9278', 'David Braz')","('person-102655', 'Dodô')","('person-226627', 'Jean Mota')","('person-183204', 'Léo Cittadini')","('person-191903', 'Alison')","('person-153217', 'Eduardo Sasha')","('person-520774', 'Rodrygo')","('person-297700', 'Gabriel')","('person-112043', 'Everson')","('person-139126', 'Luiz Otávio')","('person-111502', 'Ernandes')","('person-282377', 'Valdo')","('person-116164', 'Pio')","('person-64444', 'Juninho')","('person-176777', 'Rafael Carioca')","('person-162914', 'Wescley')","('person-65223', 'Ricardinho')","('person-409255', 'Arthur')","('person-71013', 'Felipe Azevedo')","('person-104535', 'Vladimir')","('person-218816', 'Gustavo Henrique')","('person-72164', 'Victor Ferraz')","('person-233318', 'Luiz Felipe')","('person-228041', 'Diego Pituca')","('person-3121', 'Renato')","('person-408209', 'Diogo')","('person-76643', 'E. Vecchio')","('person-328277', 'Vitor Bueno')","('person-425529', 'Arthur Gomes')","('person-92926', 'J. Copete')","('person-474975', 'Yuri Alberto')","('person-9126', 'Fernando Henrique')","('person-44196', 'Rafael Pereira')","('person-121328', 'Naldo')","('person-186344', 'Arnaldo')","('person-22388', 'J. Reina')","('person-71782', 'Roberto')","('person-34705', 'Elton')","('person-236688', 'Douglas Coutinho')",None,None,None,None,win,0,0.411765,0.269231
3,56.0,33.0,3.0,NaN,5.0,NaN,3.0,6.0,6.0,12.0,0.0,3.0,25.0,NaN,NaN,3.0,9.0,16.0,17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Sport,0,"Belo Horizonte, Minas Gerais",2018-04-15,53.0,22.0,1.0,NaN,2.0,NaN,0.0,8.0,2.0,12.0,3.0,4.0,18.0,39.0,NaN,NaN,3.0,10.0,15.0,América MG,3,18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Savio Pereira,1,Estádio Raimundo Sampaio,"('person-470560', 'Jori')","('person-9101', 'Rafael Lima')","('person-163583', 'Norberto Neto')","('person-330138', 'Messias')","('person-82899', 'Carlinhos')","('person-332878', 'Serginho')","('person-433714', 'Christian Savio')","('person-227523', 'Juninho')","('person-9150', 'Rafael Moura')","('person-32399', 'Luan')","('person-322455', 'Aylon')","('person-64369', 'Agenor')","('person-9156', 'Ernando')","('person-180820', 'Cláudio Winck')","('person-472675', 'Léo Ortiz')","('person-138100', 'Raul Prata')","('person-271473', 'Marlone')","('person-301996', 'Matheus Ferreira')","('person-180828', 'Andrigo')","('person-21094', 'Fellipe Bastos')","('person-103652', 'Anselmo')","('person-289206', 'Hygor')","('person-294307', 'Glauco')","('person-32931', 'Fernando Leal')","('person-78698', 'Aderlan')","('person-74217', 'Matheus Ferraz')","('person-8914', 'Lima')","('person-65382', 'Wesley')","('person-32918', 'Ruy')","('person-33019', 'Marquinhos')","('person-32954', 'Gerson Magrão')","('person-469303', 'Zé Ricardo')","('person-367119', 'Judivan')","('person-437641', 'Capixaba')","('person-473605', 'Mailson')","('person-327845', 'Sander')","('person-91379', 'Max')","('person-99990', 'Ronaldo Alves')","('person-460428', 'Pablo Pardal')","('person-472697', 'Nonoca')","('person-331265', 'Neto Moura')","('person-327804', 'Everton Felipe')","('person-170927', 'Gabriel')",None,None,None,win,0,0.392857,0.250000
4,49.0,33.0,NaN,NaN,5.0,NaN,2.0,7.0,2.0,15.0,1.0,NaN,29.0,NaN,NaN,3.0,10.0,14.0,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Fluminense,1,"São Paulo, São Paulo",2018-04-15,54.0,34.0,NaN,NaN,0.0,NaN,3.0,6.0,6.0,14.0,2.0,NaN,25.0,62.0,NaN,NaN,3.0,8.0,15.0,Corinthians,2,13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Anderson Daronco,1,Arena Corinthians,"('person-17304', 'Cássio')","('person-225552', 'F. Balbuena')","('person-17306', 'Fágner')","('person-32876', 'Henrique')","('person-282923', 'Sidcley')","('person-427644', 'Mateus Vital')","('person-78714', 'Rodriguinho')","('person-67276', 'Ralf')","('person-129992', 'Renê Júnior')","('person-192525', 'Á. Romero')","('person-234507', 'Clayson')","('person-8933', 'Júlio César')","('person-65394', 'Renato Chaves')","('person-187555', 'Gilberto')","('person-42129', 'Gum')","('person-474496', 'Ibañez')","('person-337005', 'Ayrton')","('person-187565', 'Jádson')","('person-301821', 'Richard')","('person-435998', 'Pedro')","('person-180800', 'J. Sornoza')","('person-290421', 'Pablo Dyego')","('person-292112', 'Caique França')","('person-398741', 'Léo Santos')","('person-329711', 'Pedro Henrique')","('person-469301', 'Guilherme Mantuan')","('person-5638', 'Danilo')","('person-476748', 'Pedrinho')","('person-433352', 'Maycon')","('person-173974', 'Gabriel')","('person-73192', 'Marquinhos Gabriel')","('person-511138', 'Matheus Matias')","('person-66297', 'Júnior Dutra')","('person-26660', 'Emerson Sheik')","('person-78768', 'Rodolfo')","('person-131042', 'Léo')","('person-472719', 'Frazan')","('person-428038', 'Marlon')","('person-415931', 'Douglas')","('person-434994', 'Mateus Norton')","('person-239932', 'Marcos Júnior')","('person-448622', 'João Carlos')","('person-471298', 'Matheus Alessandro')",None,None,None,win,0,0.322034,0.227273
5,35.0,21.0,3.0,NaN,7.0,0.0,0.0,4.0,3.0,18.0,1.0,2.0,19.0,0.0,NaN,3.0,8.0,14.0,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Atlético MG,1,"Rio de Janeiro, Rio de Janeiro",2018-04-15,56.0,39.0,4.0,NaN,8.0,1.0,2.0,6.0,9.0,11.0,1.0,3.0,28.0,67.0,1.0,NaN,3.0,5.0,20.0,Vasco,2,16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,André Luiz de Freitas Castro,1,Estádio Club de Regatas Vasco da Gama,"('person-55853', 'M. Silva')","('person-74179', 'Werley')","('person-90643', 'Rafael Galhardo')","('person-103416', 'Paulão')","('person-302496', 'Henrique')","('person-10589', 'Wagner')","('person-53471', 'Wellington')","('person-398758', 'Evander')","('person-176744', 'L. Desábato')","('person-52463', 'D. Riascos')","('person-234689', 'Yago Picachu')","('person-32329', 'Victor')","('person-462884', 'Bremer')","('person-33478', 'Patric')","('person-330130', 'Gabriel')","('person-8968', 'Fábio Santos')","('person-169690', 'J. Cazares')","('person-148555', 'R. Otero')","('person-401926', 'Gustavo Blanco')","('person-34971', 'Elias')","('person-3997', 'Ricardo Oliveira')","('person-113430', 'Luan')","('person-406795', 'Gabriel Félix')","('person-65001', 'Bruno Silva')","('person-490044', 'Ricardo Graça')","('person-234585', 'Luiz Gustavo')","('person-9052', 'Fabricio')","('person-398755', 'Andrey')","('person-112809', 'Thiago Galhardo')","('person-172278', 'Rildo')","('person-15378', 'A. Ríos')","('person-483534', 'Paulo Vitor')","('person-438314', 'Caio Monteiro')",None,"('person-437640', 'Cleiton')","('person-431779', 'Michael')","('person-537349', 'Kevin')","('person-39422', 'Felipe Santana')","('person-112519', 'Samuel Xavier')","('person-303828', 'Yago')","('person-280970', 'Lucas Cândido')","('person-443649', 'T. Andrade')","('person-9137', 'Arouca')","('person-391151', 'Roger Guedes')","('person-291015', 'Erik')","('person-474974', 'Alerrandro')",win,0,0.358025,0.390625
6,70.0,49.0,0.0,NaN,2.0,NaN,4.0,5.0,3.0,18.0,0.0,1.0,32.0,NaN,NaN,3.0,9.0,16.0,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Bahia,0,"Porto Alegre, Rio Grande do Sul",2018-04-15,59.0,39.0,2.0,NaN,2.0,NaN,2.0,6.0,4.0,15.0,2.0,1.0,23.0,44.0,NaN,NaN,3.0,7.0,19.0,Internacional,2,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Eduardo Tomaz De Aquino Valadão,1,Estádio José Pinheiro Borba (Beira-Rio),"('person-9062', 'Marcelo Lomba')","('person-86277', 'Rodrigo Moledo')","('person-184542', 'Fabiano')","('person-113709', 'V. Cuesta')","('person-472677', 'Iago')","('person-3827', ""A. D'Alessandro"")","('person-197822', 'Patrick')","('person-72088', 'Edenílson')","('person-180885', 'Rodrigo Dourado')","('person-207386', 'William Pottker')","('person-226564', 'Rossi')","('person-226394', 'Douglas Friedrich')","('person-196743', 'Tiago Pagnussat')","('person-83266', 'Nino Paraíba')","('person-121698', 'Douglas Grolli')","('person-319777', 'Léo')","('person-242453', 'Zé Rafael')","('person-78771', 'Vinicius')","('person-438600', 'Marco Antonio')","('person-99989', 'Elton')","('person-285642', 'Gregore')","('person-189034', 'Edigar Junio')","('person-458346', 'Daniel')","('person-32574', 'Uendel')","('person-380051', 'William Klaus')","('person-452042', 'Charles')","('person-234967', 'Gabriel Dias')","('person-56294', 'Camilo')","('person-395935', 'Marcinho')","('person-475983', 'Juan')","('person-535776', 'Brenner')","('person-102692', 'Wellington')","('person-187303', 'N. López')",None,"('person-78696', 'Anderson')","('person-429988', 'Rodrigo Becão')","('person-404800', 'Everson')","('person-92712', 'Edson')","('person-371205', 'João Pedro')","('person-111938', 'E. Mena')","('person-282119', 'Regis')","('person-396909', 'Flavio')","('person-17174', 'Nilton')","('person-180856', 'A. Allione')","('person-490821', 'Júnior Brumado')","('person-207544', 'Elber')",win,0,0.376471,0.235294
7,48.0,31.0,3.0,NaN,1.0,NaN,4.0,6.0,9.0,16.0,1.0,1.0,18.0,NaN,NaN,3.0,9.0,13.0,14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Chapecoense,1,"Curitiba, Paraná",2018-04-15,52.0,39.0,1.0,NaN,5.0,NaN,3.0,5.0,3.0,10.0,5.0,3.0,19.0,64.0,NaN,NaN,3.0,9.0,17.0,Atlético PR,5,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Dewson Fernando Freitas da Silva,1,Estádio Joaquim Américo Guimarães,"('person-115496', 'Santos')","('person-8964', 'Jonathan')","('person-65339', 'Thiago Carleto')","('person-404438', 'José Ivaldo')","('person-402388', 'Bruno Guimarães')","('person-84752', 'Camacho')","('person-404440', 'Matheus Rossetto')","('person-158904', 'Nikão')","('person-75811', 'E. Pavez')","('person-130585', 'Pablo Felipe')","('person-433835', 'Ribamar')","('person-327864', 'Jandrei')","('person-33252', 'Apodi')","('person-64688', 'Douglas')","('person-227670', 'Bruno Pacheco')","('person-286196', 'Rafael Thyere')","('person-9166', 'Amaral')","('person-72468', 'H. Canteros')","('person-32286', 'Márcio Araújo')","('person-148322', 'Arthur Caike')","('person-32327', 'Wellington Paulista')","('person-122231', 'Vinícius')","('person-71014', 'Felipe Alves')","('person-64987', 'Leo')","('person-460277', 'Renan Lodi')","('person-473111', 'Matheus Anjos')","('person-115497', 'Deivid')","('person-435665', 'Raphael Veiga')","('person-110278', 'Bergson')","('person-50103', 'Ederson')","('person-232650', 'Marcinho')","('person-533880', 'Demthryus')","('person-228750', 'Felipe Gedoz')","('person-441514', 'Yago César')","('person-395709', 'Elias')","('person-32679', 'Alan Ruschel')","('person-9462', 'Eduardo')","('person-328076', 'Luiz Otavio')","('person-311146', 'Vinícius Freitas')","('person-193049', 'Luiz Antonio')","('person-170348', 'Nadson')","('person-9261', 'Elicarlos')","('person-120553', 'Neném')","('person-119807', 'Júnior Santos')","('person-434106', 'Guilherme')",None,win,0,0.488889,0.227273
8,67.0,53.0,4.0,NaN,4.0,NaN,0.0,1.0,3.0,23.0,1.0,NaN,29.0,NaN,NaN,3.0,7.0,7.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Palmeiras,1,Rio de Janeiro,2018-04-16,58.0,43.0,1.0,NaN,4.0,NaN,2.0,6.0,8.0,7.0,1.0,NaN,25.0,48.0,NaN,NaN,3.0,3.0,23.0,Botafogo,1,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Ricardo Marques,1,Estádio Nilton Santos,"('person-23639', 'R. Fernández')","('person-50302', 'J. Carli')","('person-433836', 'Marcinho')","('person-383067', 'Igor Rabello')","('person-128883', 'Gilson')","('person-447817', 'Bochecha')","('person-467977', 'Matheus Fernandes')","('person-112806', 'Rodrigo Lindoso')","('person-236747', 'Brenner')","('person-207935', 'L. Valencia')","('person-330208', 'Leandro Carvalho')","('person-71262', 'Jaílson')","('person-233604', 'Antônio Carlos')","('person-73083', 'Marcos Rocha')","('person-288912', 'Thiago Martins')","('person-161746', 'Diogo Barbosa')","('person-174010', 'Lucas Lima')","('person-136155', 'Bruno Henrique')","('person-3288', 'Felipe Melo')","('person-78745', 'Willian')","('person-82057', 'Dudu')","('person-282209', 'Keno')","('person-4802', 'Jefferson')","('person-444966', 'Marcelo Conceição')","('person-32731', 'Luis Ricardo')","('person-546491', 'Jonathan')","('person-178463', 'Yago')","('person-6405', 'Dudu Cearense')","('person-362429', 'Jean')","('person-188039', 'Marcos Vinicius')","('person-71760', 'Kieza')","('person-469788', 'Pachu')","('person-492689', 'Ezequiel')","('person-32705', 'Rodrigo Pimpão')","('person-16938', 'Fernando Prass')","('person-32538', 'Weverton')","('person-191207', 'Luan')","('person-268729', 'Mayke')","('person-257112', 'Victor Luis')","('person-4734', 'Edu Dracena')","('person-2059', 'Michel Bastos')","('person-73005', 'Moisés')","('person-183186', 'Tchê Tchê')","('person-10461', 'A. Guerra')","('person-228965', 'Thiago Santos')","('person-267275', 'Deyverson')",draw,0,0.255814,0.354839

In [85]:
df_2018.to_csv('df_2018.csv')